spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    enabled: false
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://accord-react-bucket.s3-ap-southeast-2.amazonaws.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth2_route
          uri: lb://spring-server
          predicates:
            - Path=/spring/oauth2/authorization/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: oauth2CircuitBreaker
                fallbackUri: forward:/fallback/oauth2

        - id: spring-server
          uri: lb://spring-server
          predicates:
            - Path=/spring/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: springCircuitBreaker
                fallbackUri: forward:/fallback/spring

        - id: go-server
          uri: lb://go-server
          predicates:
            - Path=/go/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: goCircuitBreaker
                fallbackUri: forward:/fallback/go

        - id: signaling-server
          uri: lb://signaling-server
          predicates:
            - Path=/signaling/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: signalingCircuitBreaker
                fallbackUri: forward:/fallback/signaling

        - id: gateway-prometheus-route
          uri: http://prometheus
          predicates:
            - Path=/gateway-actuator/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: prometheusCircuitBreaker
                fallbackUri: forward:/fallback/prometheus

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
gateway:
  fallback-url: "http://accord-react-bucket.s3-website-ap-southeast-2.amazonaws.com//error"