spring:
  application:
    name: api-gateway
  security:
    enabled: false
  cloud:
    consul:
      host: 172.30.1.64
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: spring-server
          uri: lb://spring-server
          predicates:
            - Path=/spring/**
          filters:
            - StripPrefix=1
        - id: go-server
          uri: lb://go-server
          predicates:
            - Path=/go/**
          filters:
            - StripPrefix=1
        - id: signaling-server
          uri: lb://signaling-server
          predicates:
            - Path=/signaling/**
          filters:
            - StripPrefix=1

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG